// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbFkR0bAvxJtJKnnDXYFjS5rqmk_5YYfM',
    appId: '1:549971944238:web:e7c364b8881cce40b150bf',
    messagingSenderId: '549971944238',
    projectId: 'chigio-time-pcm',
    authDomain: 'chigio-time-pcm.firebaseapp.com',
    storageBucket: 'chigio-time-pcm.firebasestorage.app',
    measurementId: 'G-F7GXNE0TV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDevLtm27bXsFQdymYz9ZAfYcidABk_bXQ',
    appId: '1:549971944238:android:d6246bc70fffeb2bb150bf',
    messagingSenderId: '549971944238',
    projectId: 'chigio-time-pcm',
    storageBucket: 'chigio-time-pcm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpR24hnihw2WARiRugP9vhZbzEfPY3S0A',
    appId: '1:549971944238:ios:78d10ed04d2c0909b150bf',
    messagingSenderId: '549971944238',
    projectId: 'chigio-time-pcm',
    storageBucket: 'chigio-time-pcm.firebasestorage.app',
    iosBundleId: 'it.marcocipriani.chigioTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpR24hnihw2WARiRugP9vhZbzEfPY3S0A',
    appId: '1:549971944238:ios:78d10ed04d2c0909b150bf',
    messagingSenderId: '549971944238',
    projectId: 'chigio-time-pcm',
    storageBucket: 'chigio-time-pcm.firebasestorage.app',
    iosBundleId: 'it.marcocipriani.chigioTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbFkR0bAvxJtJKnnDXYFjS5rqmk_5YYfM',
    appId: '1:549971944238:web:d5686686a213ef4ab150bf',
    messagingSenderId: '549971944238',
    projectId: 'chigio-time-pcm',
    authDomain: 'chigio-time-pcm.firebaseapp.com',
    storageBucket: 'chigio-time-pcm.firebasestorage.app',
    measurementId: 'G-CQB3GC7SBT',
  );
}
